### ISSUE TITLE
Add retry count and retry delay options

### ISSUE THREAD

**Issue by augusto-herrmann** [sekassel-research/actions-rancher-update#8]
We've added retry count and retry delay options for Rancher 1.6.x, creating a 1.1.5 version for this script ([diff](https://github.com/economiagovbr/actions-rancher-update/compare/1.1.4...1.1.5)).

However, we can't create a pull request because there isn't a Rancher 1.6.x branch on this repository. If you create one such branch, I could create a PR targeting that branch that has already implemented this feature.

**Comment by Clashsoft** [comment]
I created the `v1` branch. Feel free to create a PR.
